on:
  issues:
    types: [opened] # change to "locked"?

jobs:

  my-tag-issue:
    runs-on: ubuntu-22.04
    name: Add issue comment
    #if: ${{ !github.event.issue.pull_request }}
    #if: ${{ github.event.issue.name == 'REPORTY' }}
    steps:
      - name: Proof of env
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: |
          echo A comment on issue $NUMBER
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: mkdir -p reports/$NUMBER && python3 ./scripts/annotation-review-report.py geneontology/exp-simple-report-generation 7 --issue $NUMBER --label REPORTY --output ./reports/$NUMBER --verbose
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit reports back to main
        with:
          commit_message: Auto-refreshing reports
          commit_user_email: sjcarbon@lbl.gov
          # Please do the dirty check, don't skip
          skip_dirty_check: false
